
server:
  port: 8088

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8086/eureka/

spring:
  application:
    name: cart-service
  datasource:
    url: jdbc:mysql://192.168.1.4:3306/cart_service?createDatabaseIfNotExist=true
#    url: jdbc:mysql://host.docker.internal:3306/cart_service?createDatabaseIfNotExist=true
    username: chandu
    password: Csv@0157
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    #      naming:
    #        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL55Dialect